title: Ronghui Lin's Homepage
page-top-title: Ronghui Lin
top-section-bg-text: Sociology
home-subtitle: Ronghui Lin&ensp;|&ensp;林蓉徽
copyright-text: '&copy; Ronghui Lin 2024-2028. All Rights Reserved.'
